title: Jinesh Meisheri # my name
description: > 
  D&T Product Manager at Best Buy
  <br><br>
  <a href = "mailto:jineshpm86@gmail.com">jineshpm86@gmail.com</a>
  <br>
  <a href = "https://www.linkedin.com/in/jinesh-meisheri/">LinkedIn Profile</a>
  <br>
  <a href = "https://www.github.com/jineshpm86/">Github</a>
theme: jekyll-theme-minimal
